### PR TITLE
Extract prometheus metrics #1

### PR DESCRIPTION
**Pull request by kuritka**
Related to #255
This is the first part of [larger](https://github.com/AbsaOSS/k8gb/compare/147-refactoring) refactoring.

 -  ~~move `Dig` to utils~~
 -  ~~move `prettyPrint()` to utils and rename to `ToJSON()`~~
 -  ~~cover `ToJSON()` by tests~~
 -  move environment variable `POD_NAMESPACE` to `depresolver`
 -  extend depresolver tests
 -  extend depresolver validators for namespace validator
 -  extract Prometheus metrics into standalone module
 -  extend Prometheus metrics with `Register()`,`Unregister()`
 -  remove `controllers/metrics.go`
 -  fix controller tests
 -  remove dead registry/k3s.yaml file (pushed by mistake)

TODO:
  - `dnsupdate` refactor, to provider pattern, will come in the next PR
  - finally, some utils will go into [gopkg](https://github.com/AbsaOSS/gopkg)
  - `IMetrics` introduction (should be implemented with #124)

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
Look good, but not sure if `ToJSON` is properly reflecting semantics... Originally the function was created just for readable struct printing...

**Review by somaritane — CHANGES_REQUESTED** [review]
I'd probably separate Dig and prettyPrint refactoring to different PRs, as they are out of context of this PR

**Comment by kuritka** [comment]
> Look good, but not sure if `ToJSON` is properly reflecting semantics... Originally the function was created just for readable struct printing...

I see, but function accepts interface so can be used to any type. Of course I can limit to structures only, and return error if passed argument is not structure. 
Do you think rename may help ? What about `ToString(a interface{}) string` ?

```go
str{"Foo", 007} => 

{
	"Name": "Foo",
	"Value": 7
}

123 => "123"
true => "true"
nil => "null"  // marshalling implicitly returns this, but can be changed. 
```

**Comment by kuritka** [comment]
> I'd probably separate Dig and prettyPrint refactoring to different PRs, as they are out of context of this PR

@somaritane, amended.

**Review by somaritane — APPROVED** [review]
lgtm 👍

**Review by ytsarev — APPROVED** [review]
looks good

**Pull request merged**
