### PR TITLE
Remove kustomize and associated make targets

### PR DESCRIPTION
**Pull request by somaritane**
Remove kustomize and associated OperatorSDK boilerplate targets

### CODE REVIEW

**Review by ytsarev — CHANGES_REQUESTED** [review]
We probably want to clean up the generated files under `config/` as well
```
find . -iname '*kustom*'
./config/webhook/kustomizeconfig.yaml
./config/webhook/kustomization.yaml
./config/rbac/kustomization.yaml
./config/default/kustomization.yaml
./config/samples/kustomization.yaml
./config/manager/kustomization.yaml
./config/certmanager/kustomizeconfig.yaml
./config/certmanager/kustomization.yaml
./config/prometheus/kustomization.yaml
./config/scorecard/kustomization.yaml
```

**Comment by somaritane** [comment]
> We probably want to clean up the generated files under `config/` as well
> 
> ```
> find . -iname '*kustom*'
> ./config/webhook/kustomizeconfig.yaml
> ./config/webhook/kustomization.yaml
> ./config/rbac/kustomization.yaml
> ./config/default/kustomization.yaml
> ./config/samples/kustomization.yaml
> ./config/manager/kustomization.yaml
> ./config/certmanager/kustomizeconfig.yaml
> ./config/certmanager/kustomization.yaml
> ./config/prometheus/kustomization.yaml
> ./config/scorecard/kustomization.yaml
> ```

@ytsarev makes sense, we get back to installations via manifests when needed, no need to have whole boilerplate

**Review by kuritka — APPROVED** [review]

**Review by k0da — APPROVED** [review]

**Comment by somaritane** [comment]
@ytsarev removed `config/` with manifest leftovers from Operator SDK, please check

**Review by ytsarev — APPROVED** [review]
lgtm

**Pull request merged**
