### PR TITLE
Migration to networking.k8s.io/v1beta1

### LINKED ISSUE #401: automate ingress validation annotation
Currently ingress object taken as is and validation is inherited from upstream. We rely on `spec.rules.http` not to be nil.

We need to find a way to instruct controller-gen to add extra markers so `spec.rules.http` is validated

### PR DESCRIPTION
**Pull request by kuritka**
- migration gslb_types and upstream_types to `networking/v1beta1`
 - migration yamls in terratest, generates warnings see: [terratest #840](https://github.com/gruntwork-io/terratest/issues/840#issue-844462699)
 - migration apiGroup in roles
 - ~~**CRD change**~~ (is already done by #425) 

closes #401

### CODE REVIEW

**Review by k0da — APPROVED** [review]
LGTM

**Review by ytsarev — COMMENTED** [review]
How the k8gb upgrade will look like with the CRD change? Can we please test permutation?

**Comment by kuritka** [comment]
@ytsarev, necessary CRD change was implemented by #425. Would be happy to implement permutation testing in scope of #349 .

**Review by k0da — DISMISSED** [review]

**Comment by ytsarev** [comment]
@kuritka it's an api group change, if the automation is not yet there we need to at least test the upgrade from previous version manually

**Review by k0da — APPROVED** [review]

**Comment by kuritka** [comment]
> @kuritka it's an api group change, if the automation is not yet there we need to at least test the upgrade from previous version manually

@ytsarev , upgrade test +  [local playground](https://github.com/AbsaOSS/k8gb/blob/master/docs/local.md) test passed

**Review by ytsarev — APPROVED** [review]

**Pull request merged**
