### PR TITLE
Update absaoss/k8s_crd CoreDNS plugin to v0.0.2

### PR DESCRIPTION
**Pull request by k0da**
This brings RecortTTL and aarch64 architecture support
(absaoss/k8s_crd:v0.0.2)

### CODE REVIEW

**Review by kuritka — DISMISSED** [review]

**Review by somaritane — CHANGES_REQUESTED** [review]
Please amend PR title with CoreDNS plugin name (`absaoss/k8s_crd`) and version (v0.0.2).

**Comment by k0da** [comment]
@somaritane isn't this visible from a change?

**Comment by somaritane** [comment]
> @somaritane isn't this visible from a change?

It is good practice to reflect the essence of PR or commit in its title.
Dependabot's produced PRs are good examples on how dependency update change title can be formatted:
https://github.com/AbsaOSS/k8gb/pull/321

**Review by somaritane — APPROVED** [review]
@k0da, can you please amend PR title and commit message title (1st line)?
The suggested text is:
`Update absaoss/k8s_crd CoreDNS plugin to v0.0.2`
Thanks.

**Review by somaritane — CHANGES_REQUESTED** [review]
@k0da, can you please amend PR title and commit message title (1st line)?
The suggested text is:
`Update absaoss/k8s_crd CoreDNS plugin to v0.0.2`
Thanks.

**Review by somaritane — APPROVED** [review]
lgtm!

**Review by ytsarev — APPROVED** [review]

**Review by kuritka — APPROVED** [review]

**Pull request merged**
