### PR TITLE
Enable coredns logging

### PR DESCRIPTION
**Pull request by ytsarev**
* Enable `log` plugin
* Move crds to `templates/crds` directory in chart
* Occasional whitespace busting

Signed-off-by: Yury Tsarev <yury.tsarev@absa.africa>

### CODE REVIEW

**Review by k0da — CHANGES_REQUESTED** [review]
Change controller-gen path for crd generation

**Review by k0da — APPROVED** [review]
LGTM

**Comment by somaritane** [comment]
> * Enable `log` plugin
> * Move crds to `templates/crds` directory in chart
> * Occasional whitespace busting
> 
> Signed-off-by: Yury Tsarev [yury.tsarev@absa.africa](mailto:yury.tsarev@absa.africa)

@ytsarev , @k0da, is `templates/crds`  change related to CoreDNS logging enablement or to #346 ?

**Comment by ytsarev** [comment]
> > * Enable `log` plugin
> > * Move crds to `templates/crds` directory in chart
> > * Occasional whitespace busting
> > 
> > Signed-off-by: Yury Tsarev [yury.tsarev@absa.africa](mailto:yury.tsarev@absa.africa)
> 
> @ytsarev , @k0da, is `templates/crds` change related to CoreDNS logging enablement or to #346 ?

Well, transitively. In this PR, It is just semantic grouping for convenience. ( `/crd` from #346 != `/templates/crd`)

**Review by somaritane — APPROVED** [review]
lgtm

**Review by kuritka — APPROVED** [review]

**Pull request merged**
